const conditionaLogicService = require('./dist/conditionalLogicService')

const submission = {
  formsAppId: 1673,
  definition: {
    id: 8176,
    name: 'Rental Assistance',
    description: '',
    organisationId: '60f0c30bc913731300000004',
    elements: [
      {
        id: 'c8fce492-d931-44b1-9da9-b71757e814e9',
        label: 'Summary',
        type: 'page',
        conditionallyShow: false,
        requiresAllConditionallyShowPredicates: false,
        elements: [
          {
            name: 'Key_Information',
            label: 'Key Information',
            type: 'heading',
            id: '98a48b9e-0c9b-4d83-8010-bc51f3a3189a',
            conditionallyShow: false,
            headingType: 3,
          },
          {
            name: 'infoWarning',
            label: 'infoWarning',
            type: 'html',
            id: '4d0651eb-c4b9-4008-9a7e-e5fc8d6c274b',
            conditionallyShow: false,
            defaultValue:
              '<p>This application is made under the (regs) rental subsidy grant for up to $1,500 for landlords who offer rent reductions to COVID-19 impacted tenants.</p><p><br></p><p>All applications must be submitted by Licensee’s (LIC) or Self Managing-Landlords and will be assessed in accordance with the eligibility requirements on the NSW Fair Trading website. A formal rent reduction must be in place with COVID-19 impacted tenants before completing this application.</p><p><br></p><p>Applicants may also be required to provide additional information to enable the application to be processed.</p><p><br></p><p>The personal information in this application will be used by the Department of Customer Service for general processing for the payment of the grant.</p><p><br></p><p>You may apply to NSW Fair Trading at any time to access and correct any of your own personal information that NSW Fair Trading may hold if that information is inaccurate, incomplete, not relevant or out of date.</p><p><br></p><p>To access or amend your personal information relating to the rental subsidy grant, applications must be made in writing to the Privacy Contact Officer, NSW Fair Trading, PO Box 972 Parramatta NSW 2124.</p><p><br></p><p>The Crimes Act 1900 provides for significant penalties, including fines and imprisonment, for making a false or misleading statement to the State in the hope of obtaining a financial benefit.</p>',
          },
          {
            name: 'Rental_Subsidy_Application',
            label: 'Rental Subsidy Application',
            type: 'heading',
            id: '26e05e03-e714-4407-9c16-5bf68e3ad69e',
            conditionallyShow: false,
            headingType: 3,
          },
          {
            name: 'keyInformation__info',
            label: 'keyInformation',
            type: 'html',
            id: 'bb58e272-ceb4-474c-8097-3c4464fc1d00',
            conditionallyShow: false,
            defaultValue:
              '<p><span class="ql-size-large">APPLYING FOR FINANCIAL ASSISTANCE</span></p><p><br></p><p>Landlords can claim the reduced rent up to a maximum of $1500 for each tenancy.&nbsp;Financial assistance is available for reductions in rent that is payable between 14 July 2021 and 11 September 2021.</p><p><br></p><p>By applying for the Rental Subsidy, a landlord will not be able to seek a reduction in their land tax payment.</p>',
          },
        ],
      },
      {
        id: 'a0136f96-c8e5-45a3-be19-57b55bed1bd1',
        label: 'Rental Information',
        type: 'page',
        conditionallyShow: false,
        requiresAllConditionallyShowPredicates: false,
        elements: [
          {
            name: 'Rental_Assistance_Form',
            label: 'Rental Information',
            type: 'heading',
            id: '31b6153c-87d4-4178-98e3-a1f3ec0a4f7c',
            conditionallyShow: false,
            headingType: 3,
          },
          {
            name: 'Are_you_a',
            label: 'Are you a',
            type: 'radio',
            required: true,
            id: 'df96ac19-8ad8-432c-be26-702905ed26c4',
            conditionallyShow: false,
            options: [
              {
                id: '41aa67fe-f5a3-4df9-bd2f-9df34c248ab6',
                value: 'Managing Agent',
                label: 'Managing Agent',
              },
              {
                id: 'd59b3e30-d3e8-4d04-9bdd-ce310495d7a0',
                value: 'Landlord',
                label: 'Landlord',
              },
            ],
            buttons: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            optionsType: 'CUSTOM',
            conditionallyShowOptions: false,
          },
          {
            name: 'agent_warning__error',
            label: 'agent warning',
            type: 'html',
            id: '1a590645-a79c-48dc-a808-ba272cde7823',
            conditionallyShow: true,
            defaultValue:
              '<p>If you have. a managing agent, please ask your managing agent to complete this form for you.</p>',
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['d59b3e30-d3e8-4d04-9bdd-ce310495d7a0'],
                type: 'OPTIONS',
              },
            ],
          },
          {
            name: 'tenancy_agreement',
            label: 'Please add your Tenancy Agreement',
            type: 'files',
            id: 'bfd3f32f-fc64-491d-8c55-a3d118536873',
            requiresAllConditionallyShowPredicates: true,
            conditionallyShow: true,
            storageType: 'private',
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['d59b3e30-d3e8-4d04-9bdd-ce310495d7a0'],
                type: 'OPTIONS',
              },
            ],
            readOnly: false,
            restrictFileTypes: false,
            minEntries: 1,
          },
          {
            name: 'Any_additional_documentation',
            label: 'Any additional documentation',
            type: 'files',
            id: '69de8daf-9503-49f1-ac80-6b839ae4ee83',
            requiresAllConditionallyShowPredicates: false,
            conditionallyShow: true,
            storageType: 'private',
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['d59b3e30-d3e8-4d04-9bdd-ce310495d7a0'],
                type: 'OPTIONS',
              },
            ],
            readOnly: false,
            restrictFileTypes: false,
          },
          {
            name: 'Property_Details',
            label: 'Property Details',
            type: 'heading',
            id: '93b8ba34-927a-44a1-82fc-e2ea561f6c2e',
            conditionallyShow: false,
            headingType: 3,
          },
          {
            name: 'Building_Name_(optional)',
            label: 'Building Name (optional)',
            type: 'text',
            required: false,
            id: 'a0e3329b-8e5f-4fb6-9317-739408985196',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
          },
          {
            name: 'Property_Address',
            label: 'Property Address',
            type: 'pointAddress',
            required: true,
            id: '4adc619e-d55f-449b-9692-c9c4e3dc1b7b',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            stateTerritoryFilter: ['NSW'],
          },
          {
            name: 'Do_you_have_a_bond_number?',
            label: 'Do you have a bond number?',
            type: 'radio',
            required: true,
            id: '5e9f28ae-0ced-469e-bc46-223ff5d2982f',
            conditionallyShow: true,
            options: [
              {
                id: '547b530c-6cad-47c6-bef7-ddf3efe9ee23',
                label: 'Yes',
                value: 'Yes',
              },
              {
                id: '2c7ef9f5-fa8c-4690-a0f9-3f5fd72d71ed',
                label: 'No',
                value: 'No',
              },
            ],
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            buttons: false,
            optionsType: 'CUSTOM',
            conditionallyShowOptions: false,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['d59b3e30-d3e8-4d04-9bdd-ce310495d7a0'],
                type: 'OPTIONS',
              },
            ],
          },
          {
            name: 'Bond_Number',
            label: 'Bond Number',
            type: 'text',
            required: true,
            id: '2c7c0919-c28e-423e-b4fa-6e8c8b30563d',
            conditionallyShow: true,
            readOnly: false,
            isDataLookup: true,
            isElementLookup: false,
            placeholderValue: 'Enter Bond Number (i.e. 1000000-2)',
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['41aa67fe-f5a3-4df9-bd2f-9df34c248ab6'],
                type: 'OPTIONS',
              },
              {
                elementId: '5e9f28ae-0ced-469e-bc46-223ff5d2982f',
                type: 'OPTIONS',
                optionIds: ['547b530c-6cad-47c6-bef7-ddf3efe9ee23'],
              },
            ],
            regexPattern: '^[A-Za-z0-9]{1}\\d{6}-[xX0-9]{1}$',
            regexMessage: 'Bond Number format is incorrect',
            regexFlags: 'gm',
            dataLookupId: 234,
          },
          {
            name: 'bond__info',
            label: 'bond info',
            type: 'html',
            id: '338d487b-361b-4ad0-9f14-77a2c4b87bbc',
            conditionallyShow: false,
            defaultValue:
              '<ul><li>If you don not know your bond number please ring xxxx-xxxx</li><li>If you have taken a bond and not lodged it with Fair Trading you will need to do this before you can proceed</li><li>If you have not taken a bond please seek assistance <a href="https://www.fairtrading.nsw.gov.au/help-centre/online-tools/make-an-enquiry" rel="noopener noreferrer" target="_blank">here</a> and lodge an online enquiry. Fair Trading will contact you to discuss your options.</li></ul>',
          },
          {
            name: 'Rent_reduction_Agreement',
            label: 'Rent Reduction Agreement',
            type: 'files',
            id: 'b255a46d-f9e6-43cf-999c-25088be8b6ff',
            conditionallyShow: false,
            storageType: 'private',
            readOnly: false,
            restrictFileTypes: false,
            minEntries: 1,
          },
        ],
      },
      {
        id: '6f74833b-39c1-4e9e-84c0-9e379222fb5f',
        label: 'Contact Details',
        type: 'page',
        conditionallyShow: false,
        requiresAllConditionallyShowPredicates: false,
        elements: [
          {
            name: 'Managing_Agent',
            label: 'Managing Agent',
            type: 'heading',
            id: '684fa958-7704-4df5-8fb5-518b7f138bf2',
            conditionallyShow: true,
            headingType: 3,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['41aa67fe-f5a3-4df9-bd2f-9df34c248ab6'],
                type: 'OPTIONS',
              },
            ],
          },
          {
            name: 'MA_Business_Name',
            label: 'Business Name',
            type: 'text',
            required: true,
            id: '2d59c81f-50bb-4a00-8879-4298773f8570',
            conditionallyShow: true,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['41aa67fe-f5a3-4df9-bd2f-9df34c248ab6'],
                type: 'OPTIONS',
              },
            ],
          },
          {
            name: 'MA_Agent_License_Number',
            label: 'Managing Agent License Number',
            type: 'text',
            required: true,
            id: 'e6c7e950-9679-4007-95f4-f0c97f243565',
            conditionallyShow: true,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['41aa67fe-f5a3-4df9-bd2f-9df34c248ab6'],
                type: 'OPTIONS',
              },
            ],
            hint: 'This is the license number of the managing agent entity',
            placeholderValue:
              'Please enter the license number of the managing agent entity',
            regexPattern: '^\\d{8}$|^\\d{10}$',
            regexFlags: 'gm',
            regexMessage: 'Please enter a valid License Number',
          },
          {
            name: 'MA_First_Name',
            label: 'First Name',
            type: 'text',
            required: false,
            id: 'cfa02801-24a7-4f7b-802f-9f2745b50a47',
            requiresAllConditionallyShowPredicates: false,
            conditionallyShow: true,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['41aa67fe-f5a3-4df9-bd2f-9df34c248ab6'],
                type: 'OPTIONS',
              },
            ],
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
          },
          {
            name: 'MA_Last_Name',
            label: 'Last Name',
            type: 'text',
            required: true,
            id: '26da5d37-4a3c-4768-8d6f-7ae8a5c95f11',
            conditionallyShow: true,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['41aa67fe-f5a3-4df9-bd2f-9df34c248ab6'],
                type: 'OPTIONS',
              },
            ],
          },
          {
            name: 'MA_Email',
            label: 'Email Address',
            type: 'email',
            required: false,
            id: 'c6b05333-659e-4de7-a3f0-c5de322b794f',
            conditionallyShow: true,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['41aa67fe-f5a3-4df9-bd2f-9df34c248ab6'],
                type: 'OPTIONS',
              },
            ],
          },
          {
            name: 'MA_Mobile_Number',
            label: 'Mobile Number',
            type: 'telephone',
            required: true,
            id: '797cbda6-c616-430b-85df-f891d36a6a73',
            conditionallyShow: true,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            regexPattern:
              '^\\({0,1}((0|\\+61)(2|4|3|7|8)){0,1}\\){0,1}(\\ |-){0,1}[0-9]{2}(\\ |-){0,1}[0-9]{2}(\\ |-){0,1}[0-9]{1}(\\ |-){0,1}[0-9]{3}$',
            regexFlags: 'gm',
            regexMessage: 'Please enter a valid Australian phone number',
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['41aa67fe-f5a3-4df9-bd2f-9df34c248ab6'],
                type: 'OPTIONS',
              },
            ],
          },
          {
            name: 'Landlord_Details',
            label: 'Landlord Details',
            type: 'heading',
            id: '60aa6e0d-b803-4138-b642-64372f2c62fc',
            conditionallyShow: false,
            headingType: 3,
          },
          {
            name: 'Business_Name',
            label: 'Business Name (if applicable)',
            type: 'text',
            required: false,
            id: '47bd7c89-02e5-4b31-b055-0f3b29963998',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
          },
          {
            name: 'L_First_Name',
            label: 'First Name',
            type: 'text',
            required: true,
            id: 'f6f3ba47-9a49-47af-a4c6-9274de9fd260',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
          },
          {
            name: 'L_Last_Name',
            label: 'Last Name',
            type: 'text',
            required: false,
            id: '31016306-7050-436a-a559-0ba49fb3523c',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
          },
          {
            name: 'L_Address',
            label: 'Address',
            type: 'pointAddress',
            required: true,
            id: 'de727114-df4f-43fc-b75b-234f94fb3bcb',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
          },
          {
            name: 'L_Email',
            label: 'Email Address',
            type: 'email',
            required: true,
            id: '3306f2ef-f13e-4021-9235-481ac51f4d69',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
          },
          {
            name: 'L_Mobile_Number',
            label: 'Mobile Number',
            type: 'telephone',
            required: true,
            id: '79b45af3-080b-42f7-b213-2ae3238ba9e9',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
          },
          {
            name: 'Your_Details',
            label: 'Your Details',
            type: 'heading',
            id: '15823e6f-7424-4f01-bc7d-991f819260ef',
            conditionallyShow: false,
            headingType: 3,
          },
          {
            name: 'Are_your_details_the_same_as_the_managing_agent?',
            label: 'My details are the same as the managing agent?',
            type: 'boolean',
            required: false,
            id: '786ce1b2-6873-4d65-ae3e-cf3e285efb9a',
            requiresAllConditionallyShowPredicates: false,
            conditionallyShow: true,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['41aa67fe-f5a3-4df9-bd2f-9df34c248ab6'],
                type: 'OPTIONS',
              },
            ],
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            defaultValue: false,
          },
          {
            name: 'My_Details_are_the_same_as_the_Landlord',
            label: 'My details are the same as the Landlord',
            type: 'boolean',
            required: false,
            id: 'f6f0d683-5472-48d2-b0c7-36ac9b7e4cb2',
            requiresAllConditionallyShowPredicates: false,
            conditionallyShow: true,
            conditionallyShowPredicates: [
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                optionIds: ['d59b3e30-d3e8-4d04-9bdd-ce310495d7a0'],
                type: 'OPTIONS',
              },
            ],
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            defaultValue: false,
          },
          {
            name: 'First_Name2',
            label: 'First Name',
            type: 'text',
            required: true,
            id: '0d5f8612-a3a4-4c2a-867b-03f8839847b7',
            conditionallyShow: true,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: '786ce1b2-6873-4d65-ae3e-cf3e285efb9a',
                type: 'VALUE',
                hasValue: false,
              },
              {
                elementId: 'f6f0d683-5472-48d2-b0c7-36ac9b7e4cb2',
                type: 'VALUE',
                hasValue: false,
              },
            ],
          },
          {
            name: 'Last_Name2',
            label: 'Last Name',
            type: 'text',
            required: true,
            id: 'ca512d80-7be5-46d1-bb95-5be034efedef',
            conditionallyShow: true,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: '786ce1b2-6873-4d65-ae3e-cf3e285efb9a',
                type: 'VALUE',
                hasValue: false,
              },
              {
                elementId: 'f6f0d683-5472-48d2-b0c7-36ac9b7e4cb2',
                type: 'VALUE',
                hasValue: false,
              },
            ],
          },
          {
            name: 'A_Email',
            label: 'Email Address',
            type: 'email',
            required: true,
            id: 'a5969c13-2c13-4391-a0e5-2fa0a53adef2',
            conditionallyShow: true,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: '786ce1b2-6873-4d65-ae3e-cf3e285efb9a',
                type: 'VALUE',
                hasValue: false,
              },
              {
                elementId: 'f6f0d683-5472-48d2-b0c7-36ac9b7e4cb2',
                type: 'VALUE',
                hasValue: false,
              },
            ],
          },
          {
            name: 'A_Mobile_Number',
            label: 'Mobile Number',
            type: 'telephone',
            required: true,
            id: '7568124c-b580-458d-b5d8-27da5c4ae354',
            conditionallyShow: true,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: '786ce1b2-6873-4d65-ae3e-cf3e285efb9a',
                type: 'VALUE',
                hasValue: false,
              },
              {
                elementId: 'f6f0d683-5472-48d2-b0c7-36ac9b7e4cb2',
                type: 'VALUE',
                hasValue: false,
              },
            ],
          },
          {
            name: 'Agent_License_Number',
            label: 'Agent License Number',
            type: 'text',
            required: true,
            id: '8c8d2304-dc15-4957-a368-3be995d4d216',
            requiresAllConditionallyShowPredicates: false,
            conditionallyShow: true,
            conditionallyShowPredicates: [
              {
                elementId: '786ce1b2-6873-4d65-ae3e-cf3e285efb9a',
                type: 'VALUE',
                hasValue: false,
              },
              {
                elementId: 'f6f0d683-5472-48d2-b0c7-36ac9b7e4cb2',
                type: 'VALUE',
                hasValue: false,
              },
            ],
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            regexPattern: '^\\d{8}$|^\\d{10}$',
            regexFlags: 'gm',
            regexMessage: 'Please enter a valid License Number',
          },
        ],
      },
      {
        id: '430b70a4-dd38-45ad-9034-107cdee89dc3',
        label: 'Tenant Details',
        type: 'page',
        conditionallyShow: false,
        requiresAllConditionallyShowPredicates: false,
        elements: [
          {
            name: 'Tenant_Details',
            label: 'Tenant Details',
            type: 'heading',
            id: '52492a80-074d-4c78-84f7-dc49cb06ab3e',
            conditionallyShow: false,
            headingType: 3,
          },
          {
            name: 'Tenants',
            label: 'Tenants',
            type: 'repeatableSet',
            required: false,
            id: '311277a6-992d-47ca-89f9-39782428873f',
            conditionallyShow: false,
            elements: [
              {
                name: 'First_name',
                label: 'First name',
                type: 'text',
                required: false,
                id: '59938483-0494-4976-8f57-10069ce73db3',
                conditionallyShow: false,
                readOnly: false,
                isDataLookup: false,
                isElementLookup: false,
              },
              {
                name: 'Last_name',
                label: 'Last name',
                type: 'text',
                required: false,
                id: 'c0b08fa0-e957-4f4f-8a53-bee618e3c6e1',
                conditionallyShow: false,
                readOnly: false,
                isDataLookup: false,
                isElementLookup: false,
              },
              {
                name: 'T_Email',
                label: 'Email Address',
                type: 'email',
                required: false,
                id: '5c686d94-b26c-455a-bb7c-b2283974ea7e',
                conditionallyShow: false,
                readOnly: false,
                isDataLookup: false,
                isElementLookup: false,
              },
              {
                name: 'T_Mobile_Number',
                label: 'Mobile Number',
                type: 'telephone',
                required: false,
                id: 'c4b7ce7b-e91b-4438-87be-625df70e4aed',
                conditionallyShow: false,
                readOnly: false,
                isDataLookup: false,
                isElementLookup: false,
              },
              {
                name: 'tenant_rental_reduction',
                label: 'Tenant has rental agreement reduction',
                type: 'boolean',
                required: false,
                id: '6b326373-8ebb-49c4-aed2-7c116f8fda8d',
                conditionallyShow: false,
                defaultValue: true,
                readOnly: false,
                isDataLookup: false,
                isElementLookup: false,
              },
            ],
            readOnly: false,
            minSetEntries: 1,
            addSetEntryLabel: 'Add a Tenant',
            removeSetEntryLabel: 'Remove',
          },
        ],
      },
      {
        id: '56d3d2b8-7903-4fba-8ce2-fafac483fcca',
        label: 'Payment Details',
        type: 'page',
        conditionallyShow: false,
        requiresAllConditionallyShowPredicates: false,
        elements: [
          {
            name: 'Payment_Details',
            label: 'Payment Details',
            type: 'heading',
            id: 'a7014fc5-ee8e-4571-bcf9-dd1a47aadf05',
            conditionallyShow: false,
            headingType: 3,
          },
          {
            name: 'BSB',
            label: 'BSB',
            type: 'text',
            required: true,
            id: 'de62a135-da6e-4709-828d-a0d341f285c8',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            regexPattern: '^[0-9]{6}$',
            regexMessage: 'BSB Number must be six digits',
            placeholderValue: 'Please enter your BSB number',
          },
          {
            name: 'Account_Number',
            label: 'Account Number',
            type: 'text',
            required: false,
            id: '8357690c-3c96-464a-89c0-816ae212d6b9',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            placeholderValue: 'Please enter the account number',
          },
          {
            name: 'Account_Name',
            label: 'Account Name',
            type: 'text',
            required: false,
            id: 'b8de4557-328b-478b-97eb-cc87e62af03d',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            placeholderValue: 'Please enter the name of the account',
          },
          {
            name: 'Summary_of_agreed_rental_deduction',
            label: 'Claim',
            type: 'heading',
            id: 'f9c95b17-8b24-4797-b065-6294bdcb0019',
            conditionallyShow: false,
            headingType: 3,
          },
          {
            name: 'Claim_Amount',
            label: 'Total $ Claim Amount',
            type: 'number',
            required: false,
            id: '9556be63-c492-47a5-9378-2a540c640e72',
            conditionallyShow: false,
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            isSlider: false,
            isInteger: false,
            maxNumber: 1500,
            placeholderValue: 'Please enter the amount that you wish to claim',
          },
        ],
      },
      {
        id: '4292122a-13a7-46d4-9b49-124056997c5d',
        label: 'Declaration',
        type: 'page',
        conditionallyShow: false,
        requiresAllConditionallyShowPredicates: false,
        elements: [
          {
            name: 'Declaration',
            label: 'DECLARATION',
            type: 'heading',
            id: 'f31ab942-68ba-413a-a7e5-e84e21775f71',
            conditionallyShow: false,
            headingType: 3,
          },
          {
            name: 'Declare',
            label: 'Declaration',
            type: 'checkboxes',
            required: true,
            id: '1529a125-9c1b-4afb-adda-ba2952306be4',
            conditionallyShow: false,
            options: [
              {
                id: '78322622-b3d0-4f3b-afa5-66e569130203',
                label: 'I acknowledge and agree that',
                value: 'I acknowledge and agree that',
              },
            ],
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
            buttons: false,
            optionsType: 'CUSTOM',
            conditionallyShowOptions: false,
            canToggleAll: false,
          },
          {
            name: 'declaration_Information',
            label: 'declaration Information',
            type: 'html',
            id: '0a54786c-7392-4eba-a8c2-377c4e6afc85',
            conditionallyShow: false,
            defaultValue:
              '<p><span style="background-color: transparent; color: rgb(0, 0, 0);">i. I will use the financial assistance for its named purpose.</span></p><p><br></p><p><span style="background-color: transparent; color: rgb(0, 0, 0);">ii. I have read the NSW Fair Trading website – Financial Support for Landlords and understand the application will be assessed in accordance with the eligibility requirements.</span></p><p><br></p><p><span style="background-color: transparent; color: rgb(0, 0, 0);">iii. personal information provided in this form will be used by NSW Fair Trading to assess the application for financial assistance under the Rental Subsidy Grant.</span></p><p><br></p><p><span style="background-color: transparent; color: rgb(0, 0, 0);">iv. the personal information provided in this form may also be used in connection with the general administration of the grant, including reporting to other government agencies.</span></p><p><br></p><p><span style="background-color: transparent; color: rgb(0, 0, 0);">v. I have a right to seek access to, and correction of, information supplied in this form.</span></p><p><br></p><p><span style="background-color: transparent; color: rgb(0, 0, 0);">vi. the Crimes Act 1900 provides for significant penalties, including fines and imprisonment, for making a false or misleading statement to the State in the hope of obtaining a financial benefit.</span></p>',
          },
          {
            name: 'First_Name__repeatheading',
            label: 'First Name',
            type: 'html',
            id: 'a1a97a1f-27d7-4927-8cde-e7fca78c1877',
            conditionallyShow: false,
            defaultValue: '<p>First Name</p>',
          },
          {
            name: 'S_A_First_Name__repeat',
            label: 'First Name Applicant',
            type: 'summary',
            required: false,
            id: 'd15dd6d0-1356-4376-ae06-eec94d3717a7',
            conditionallyShow: true,
            elementIds: ['0d5f8612-a3a4-4c2a-867b-03f8839847b7'],
            readOnly: false,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: '786ce1b2-6873-4d65-ae3e-cf3e285efb9a',
                type: 'VALUE',
                hasValue: false,
              },
              {
                elementId: 'f6f0d683-5472-48d2-b0c7-36ac9b7e4cb2',
                type: 'VALUE',
                hasValue: false,
              },
            ],
          },
          {
            name: 'S_MA_First_Name__repeat',
            label: 'First Name Managing Agent',
            type: 'summary',
            required: false,
            id: '97be4af7-026a-4b30-a043-38356d09f411',
            conditionallyShow: true,
            elementIds: ['cfa02801-24a7-4f7b-802f-9f2745b50a47'],
            readOnly: false,
            requiresAllConditionallyShowPredicates: true,
            conditionallyShowPredicates: [
              {
                elementId: '786ce1b2-6873-4d65-ae3e-cf3e285efb9a',
                type: 'VALUE',
                hasValue: true,
              },
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                type: 'OPTIONS',
                optionIds: ['41aa67fe-f5a3-4df9-bd2f-9df34c248ab6'],
              },
            ],
          },
          {
            name: 'S_L_First_Name__repeat',
            label: 'First Name Landlord',
            type: 'summary',
            required: false,
            id: 'a46399b6-b1a7-447e-948c-d2cad090613d',
            conditionallyShow: true,
            elementIds: ['f6f3ba47-9a49-47af-a4c6-9274de9fd260'],
            readOnly: false,
            requiresAllConditionallyShowPredicates: true,
            conditionallyShowPredicates: [
              {
                elementId: 'f6f0d683-5472-48d2-b0c7-36ac9b7e4cb2',
                type: 'VALUE',
                hasValue: true,
              },
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                type: 'OPTIONS',
                optionIds: ['d59b3e30-d3e8-4d04-9bdd-ce310495d7a0'],
              },
            ],
          },
          {
            name: 'Last_Name__repeatheading',
            label: 'Last Name',
            type: 'html',
            id: '056a9a4a-24cc-471f-8811-8634f634dbdb',
            conditionallyShow: false,
            defaultValue: '<p>Last Name</p>',
          },
          {
            name: 'S_A_Last_Name__repeat',
            label: 'Last Name Applicant',
            type: 'summary',
            required: false,
            id: '87450937-137e-4efc-ab17-280c9d761224',
            conditionallyShow: true,
            elementIds: ['ca512d80-7be5-46d1-bb95-5be034efedef'],
            readOnly: false,
            requiresAllConditionallyShowPredicates: false,
            conditionallyShowPredicates: [
              {
                elementId: '786ce1b2-6873-4d65-ae3e-cf3e285efb9a',
                type: 'VALUE',
                hasValue: false,
              },
              {
                elementId: 'f6f0d683-5472-48d2-b0c7-36ac9b7e4cb2',
                type: 'VALUE',
                hasValue: false,
              },
            ],
          },
          {
            name: 'S_MA_Last_Name__repeat',
            label: 'Last Name Managing Agent',
            type: 'summary',
            required: false,
            id: 'f6c8fac4-8d9b-4fd9-bd42-9df97a041591',
            conditionallyShow: true,
            elementIds: ['26da5d37-4a3c-4768-8d6f-7ae8a5c95f11'],
            readOnly: false,
            requiresAllConditionallyShowPredicates: true,
            conditionallyShowPredicates: [
              {
                elementId: '786ce1b2-6873-4d65-ae3e-cf3e285efb9a',
                type: 'VALUE',
                hasValue: true,
              },
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                type: 'OPTIONS',
                optionIds: ['41aa67fe-f5a3-4df9-bd2f-9df34c248ab6'],
              },
            ],
          },
          {
            name: 'S_L_Last_Name__repeat',
            label: 'Last Name Landlord',
            type: 'summary',
            required: false,
            id: '4abedbf3-7fa9-4a23-adba-a26f459c8d55',
            conditionallyShow: true,
            elementIds: ['31016306-7050-436a-a559-0ba49fb3523c'],
            readOnly: false,
            requiresAllConditionallyShowPredicates: true,
            conditionallyShowPredicates: [
              {
                elementId: 'f6f0d683-5472-48d2-b0c7-36ac9b7e4cb2',
                type: 'VALUE',
                hasValue: true,
              },
              {
                elementId: 'df96ac19-8ad8-432c-be26-702905ed26c4',
                type: 'OPTIONS',
                optionIds: ['d59b3e30-d3e8-4d04-9bdd-ce310495d7a0'],
              },
            ],
          },
          {
            name: 'Date',
            label: 'Date',
            type: 'date',
            required: false,
            id: 'f0937b4f-be41-4ea0-add2-b332c9666355',
            conditionallyShow: false,
            defaultValue: 'NOW',
            readOnly: false,
            isDataLookup: false,
            isElementLookup: false,
          },
          {
            name: 'Signature',
            label: 'Signature',
            type: 'draw',
            required: false,
            id: '3b690d90-53a1-4631-9e75-73f2b2bc80e3',
            conditionallyShow: false,
            storageType: 'private',
            readOnly: false,
          },
          {
            name: 'Robot',
            label: 'Robot',
            type: 'captcha',
            required: false,
            id: '27fb0005-aa3d-43ac-977a-81395b3e2ee0',
            conditionallyShow: false,
            readOnly: false,
          },
        ],
      },
    ],
    isAuthenticated: false,
    submissionEvents: [
      {
        type: 'ONEBLINK_API',
        configuration: {
          apiId: 'nswfairtrading-rental-assistance.api.oneblink.io',
          apiEnvironment: 'dev',
          apiEnvironmentRoute: '/callback/notifications/email/applicant',
        },
        isDraft: false,
        conditionallyExecute: false,
        requiresAllConditionallyExecutePredicates: false,
      },
      {
        type: 'ONEBLINK_API',
        configuration: {
          apiId: 'nswfairtrading-rental-assistance.api.oneblink.io',
          apiEnvironment: 'dev',
          apiEnvironmentRoute: '/callback/notifications/email/landlord',
        },
        isDraft: false,
        conditionallyExecute: false,
        requiresAllConditionallyExecutePredicates: false,
      },
      {
        type: 'ONEBLINK_API',
        configuration: {
          apiId: 'nswfairtrading-rental-assistance.api.oneblink.io',
          apiEnvironment: 'dev',
          apiEnvironmentRoute: '/callback/notifications/email/managing-agent',
        },
        isDraft: false,
        conditionallyExecute: false,
        requiresAllConditionallyExecutePredicates: false,
      },
      {
        type: 'ONEBLINK_API',
        configuration: {
          apiId: 'nswfairtrading-rental-assistance.api.oneblink.io',
          apiEnvironment: 'dev',
          apiEnvironmentRoute: '/callback/notifications/email/tenant',
        },
        isDraft: false,
        conditionallyExecute: false,
        requiresAllConditionallyExecutePredicates: false,
      },
      {
        type: 'ONEBLINK_API',
        configuration: {
          apiId: 'nswfairtrading-rental-assistance.api.oneblink.io',
          apiEnvironment: 'dev',
          apiEnvironmentRoute: '/callback/notifications/sms/applicant',
        },
        isDraft: false,
        conditionallyExecute: false,
        requiresAllConditionallyExecutePredicates: false,
      },
      {
        type: 'ONEBLINK_API',
        configuration: {
          apiId: 'nswfairtrading-rental-assistance.api.oneblink.io',
          apiEnvironment: 'dev',
          apiEnvironmentRoute: '/callback/notifications/sms/landlord',
        },
        isDraft: false,
        conditionallyExecute: false,
        requiresAllConditionallyExecutePredicates: false,
      },
      {
        type: 'ONEBLINK_API',
        configuration: {
          apiId: 'nswfairtrading-rental-assistance.api.oneblink.io',
          apiEnvironment: 'dev',
          apiEnvironmentRoute: '/callback/notifications/sms/managing-agent',
        },
        isDraft: false,
        conditionallyExecute: false,
        requiresAllConditionallyExecutePredicates: false,
      },
      {
        type: 'ONEBLINK_API',
        configuration: {
          apiId: 'nswfairtrading-rental-assistance.api.oneblink.io',
          apiEnvironment: 'dev',
          apiEnvironmentRoute: '/callback/notifications/sms/tenant',
        },
        isDraft: false,
        conditionallyExecute: false,
        requiresAllConditionallyExecutePredicates: false,
      },
    ],
    createdAt: '2021-07-21T05:56:54.000Z',
    updatedAt: '2021-07-25T23:45:12.000Z',
    isMultiPage: true,
    postSubmissionAction: 'URL',
    redirectUrl:
      'https://nswfairtrading-rental-assistance-dev.app.oneblink.io/forms/8180?preFillData={%22referenceNumber%22:%22{EXTERNAL_ID}%22}',
    cancelAction: 'CLOSE',
    isInfoPage: false,
    formsAppEnvironmentId: 525,
    tags: [],
    formsAppIds: [1673],
  },
  submission: {
    Key_Information: true,
    infoWarning: true,
    Rental_Subsidy_Application: true,
    keyInformation__info: true,
    Rental_Assistance_Form: true,
    Are_you_a: 'Managing Agent',
    Property_Details: true,
    Property_Address: {
      dataset: 'gnaf',
      geo: {
        geoDatumCode: 'GDA94',
        geoFeature: 'PROPERTY CENTROID',
        geometry: { coordinates: [151.34117339, -33.42868167], type: 'Point' },
      },
      addressDetails: {
        cadastralIdentifier: '2/219637',
        formattedAddress: '40 MANN ST, GOSFORD NSW 2250',
        localityName: 'GOSFORD',
        lotIdentifier: '2',
        postcode: '2250',
        stateTerritory: 'NSW',
        streetName: 'MANN',
        streetNumber1: '40',
        streetType: 'ST',
      },
      addressId: 'GANSW704843090',
      addressRecordType: 'Primary',
      asgsMain: {
        2016: {
          mbId: '11204391700',
          sa1Id: '10201103224',
          sa2Id: '102011032',
          sa3Id: '10201',
          sa4Id: '102',
        },
      },
      commonwealthElectorate: {
        commElectoralName: 'ROBERTSON',
        commElectoralPid: 'NSW5',
      },
      localGovernmentArea: {
        lgaName: 'CENTRAL COAST COUNCIL',
        lgaShortName: 'CENTRAL COAST',
        lgaPid: 'NSW327',
      },
      stateElectorate: [
        {
          stateElectoralName: 'GOSFORD',
          stateElectoralPid: 'NSW178',
          stateElectoralType: 'Legislative Assembly',
          stateElectoralClassCode: '2',
        },
      ],
      messages: [
        {
          code: 'NONE',
          description:
            'An error occurred while requesting mailAddress for GANSW704843090 Error. Response contains only notes: addressFound: FALSE',
          message: 'Error. Response contains only notes: addressFound: FALSE',
          severity: 'INFO',
        },
      ],
      cadastralParcels: [{ propId: '64519', parcelId: ['2//DP219637'] }],
    },
    Bond_Number: '1000146-4',
    bond__info: true,
    Rent_reduction_Agreement: [
      {
        s3: {
          bucket: 'nswfairtrading.forms.oneblink.io',
          key: 'submissions/8176/attachments/13318f6a-798f-4cf8-86aa-5625b577f395',
          region: 'ap-southeast-2',
        },
        url: 'https://auth-api.blinkm.io/submissions/8176/attachments/13318f6a-798f-4cf8-86aa-5625b577f395',
        contentType: 'image/jpeg',
        fileName: 'NSWGov.jpg',
        id: '13318f6a-798f-4cf8-86aa-5625b577f395',
        isPrivate: true,
      },
    ],
    Managing_Agent: true,
    MA_Business_Name: '1',
    MA_Agent_License_Number: '12345678',
    MA_Last_Name: '1',
    MA_Mobile_Number: '0423149533',
    Landlord_Details: true,
    L_First_Name: '1',
    L_Address: {
      dataset: 'gnaf',
      geo: {
        geoDatumCode: 'GDA94',
        geoFeature: 'PROPERTY CENTROID',
        geometry: { coordinates: [151.34117339, -33.42868167], type: 'Point' },
      },
      addressDetails: {
        cadastralIdentifier: '2/219637',
        formattedAddress: '40 MANN ST, GOSFORD NSW 2250',
        localityName: 'GOSFORD',
        lotIdentifier: '2',
        postcode: '2250',
        stateTerritory: 'NSW',
        streetName: 'MANN',
        streetNumber1: '40',
        streetType: 'ST',
      },
      addressId: 'GANSW704843090',
      addressRecordType: 'Primary',
      asgsMain: {
        2016: {
          mbId: '11204391700',
          sa1Id: '10201103224',
          sa2Id: '102011032',
          sa3Id: '10201',
          sa4Id: '102',
        },
      },
      commonwealthElectorate: {
        commElectoralName: 'ROBERTSON',
        commElectoralPid: 'NSW5',
      },
      localGovernmentArea: {
        lgaName: 'CENTRAL COAST COUNCIL',
        lgaShortName: 'CENTRAL COAST',
        lgaPid: 'NSW327',
      },
      stateElectorate: [
        {
          stateElectoralName: 'GOSFORD',
          stateElectoralPid: 'NSW178',
          stateElectoralType: 'Legislative Assembly',
          stateElectoralClassCode: '2',
        },
      ],
      messages: [
        {
          code: 'NONE',
          description:
            'An error occurred while requesting mailAddress for GANSW704843090 Error. Response contains only notes: addressFound: FALSE',
          message: 'Error. Response contains only notes: addressFound: FALSE',
          severity: 'INFO',
        },
      ],
      cadastralParcels: [{ propId: '64519', parcelId: ['2//DP219637'] }],
    },
    L_Email: 'kieren@oneblink.io',
    L_Mobile_Number: '0423149533',
    Your_Details: true,
    'Are_your_details_the_same_as_the_managing_agent?': true,
    Tenant_Details: true,
    Tenants: [{ tenant_rental_reduction: true }],
    Payment_Details: true,
    BSB: '123456',
    Summary_of_agreed_rental_deduction: true,
    Declaration: true,
    Declare: ['I acknowledge and agree that'],
    declaration_Information: true,
    First_Name__repeatheading: true,
    Last_Name__repeatheading: true,
    S_MA_Last_Name__repeat: ['1'],
    Date: '2021-07-26',
    Signature: {
      s3: {
        bucket: 'nswfairtrading.forms.oneblink.io',
        key: 'submissions/8176/attachments/9745cf6a-a0ef-4f26-a273-d0caa3ec08e1',
        region: 'ap-southeast-2',
      },
      url: 'https://auth-api.blinkm.io/submissions/8176/attachments/9745cf6a-a0ef-4f26-a273-d0caa3ec08e1',
      contentType: 'image/png',
      fileName: 'signature.png',
      id: '9745cf6a-a0ef-4f26-a273-d0caa3ec08e1',
      isPrivate: true,
    },
    Robot:
      '03AGdBq26jeDV0MTH45NJ-lhzHiX9RWJuomBtPBtiwFwaA_qO47mcYEm88jnFj9wDsB4Vkw-PE0IwhSzzBrRSj6L0vXAc_vEvSPEhrjUcWweZ2-ni9ih4pNDrHT__hA-DpEoLxvXrmYNR9b3gm6XlbRLHp6FZZRukwQsoQpwqCyvz4td_r3oP7qTh9YUnKpu8nOfxUVSfcsJj1n7TLam5yK1Bx8umrgKt70JB5nQyml-Ut1WjmOtIOZiRaMMomBDt0EZeN_BsV7Jdut-yXV-vmqs5C1kuNCZVfwZNndYfFYcnGz34e0Lw6tRjm07znKkBtlfWZGXaPeRsxYI16Af2pepBNLrtnBMtYQn6IfBmokF_nqjI3aWUD2ZsKJAotWIorGxGdCmUv4lUq9uC0WxS8LeW_tXp6wOYKWXqUpCQg4c6CjMISlQ406qwI-MUhaFYJgtvF4bWCimxgoikg_uQDJ5xAbNHon34G6WfkaCCQx4WBJNhvVgWPp9g',
  },
  submissionTimestamp: '2021-07-26T01:47:51.701Z',
  user: null,
  device: {
    type: 'BROWSER',
    appCodeName: 'Mozilla',
    appName: 'Netscape',
    appVersion:
      '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36',
    cookieEnabled: true,
    hardwareConcurrency: 8,
    language: 'en-US',
    maxTouchPoints: 0,
    platform: 'Win32',
    userAgent:
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36',
    vendor: 'Google Inc.',
    vendorSub: '',
    webdriver: false,
  },
}
